### ISSUE TITLE
Can I work on this project with you? Thanks.

### ISSUE THREAD

**Issue by lumauser** [dacoder101/jlox-interpreter#1]
I was just wondering if you were interested in working on this project with me. Thanks. Oh I also found this https://github.com/ryanq/jlox some random guy made a jlox-interpreter too. Maybe we can salvage some code from there idk even though all the code is in the book.

**Comment by dacoder101** [comment]
All of the code is written in the book, I have made a couple of changes (added block comments and a couple of other arithmetic tokens that are found in Python), so it wouldn't be really ideal to copy it.

_I was just wondering if you were interested in working on this project with me._ Are you going to start your own and want me to work on it with you or do you want to collaborate on this one?

**Comment by lumauser** [comment]
I don't feel like starting a new one I think I'm fine with collaborating on your repository instead.  Thanks!
